# Generated by Django 6.1 on 2026-09-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_v5_saved_searches'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='properties__receive_869cf2_idx',
            old_name='props_msg_receiver_read_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='properties__sender__a58046_idx',
            old_name='props_msg_sender_sent_idx',
        ),
    ]
